services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mongo:latest 
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: app_user
      MONGO_INITDB_ROOT_PASSWORD: app_password
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data: